### ISSUE TITLE
stepIndicator.setOffset bug

### ISSUE THREAD

**Issue by liaodongxiaoxiao** [layerlre/StepIndicator#1]
in the demo ,like this status:
![screenshot_2016-08-23-10-59-18-169_stepindicator](https://cloud.githubusercontent.com/assets/4077745/17878930/e012b770-6920-11e6-83da-9afe8f13e0e7.png)
when I touch first circle view：
![screenshot_2016-08-23-10-59-27-167_stepindicator](https://cloud.githubusercontent.com/assets/4077745/17878951/15e8d640-6921-11e6-96f8-22c043d28ef8.png)
Step not to first.

![default](https://cloud.githubusercontent.com/assets/4077745/17879116/b316096a-6921-11e6-89b5-43d66bbe5f42.PNG)

private void setOffset(float offset, int position) {
        this.offset = offset;
        offsetPixel = Math.round(stepDistance \* offset);
        if (currentStepPosition > position) {
            offsetPixel = offsetPixel - stepDistance;
        } else if(offset==0){
            //?????
            currentStepPosition = position;
        }

```
    invalidate();
}
```

**Comment by layerlre** [comment]
Thanks.
Fixed in 1.1.0
